# -*- coding: utf-8 -*-
"""626_F1_PRACTICAL 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15f7xJ9jjrGZOIbbrO22xAU3KKvFmlZcl
"""

#NAME : NEHAAL ANIL PANDEY
#ROLL NO. : 626
#BATCH : F1
#DATE : 31/05/2021.

#PRACTICAL 2.1 : Write a Python program for following conditions.
# If n is single digit print square of it.
# If n is two digit print square root of it.
# If n is three digit print cube root of it.

                              
#INPUT           
print("WELCOME!!!")                                #print function prints everything under double quotes.
n = float(input("ENTER THE VALUE OF n : "))        #taking the value of m from the user.
if n<10.00 :                                       #using conditional statement if to check the given condition.
    print(n*n)                                     #if the condition stands true, the square of the n is printed.
elif n>10.00 and n<100.00 :                        #else if this condition is true, we print the square root of the number.
    print(n**0.5)
elif n>100.00 and n<1000.00 :                      #else if this condition is true, print cuberoot of n. 
    print(format(n**0.333334,".2f"))
else :                                             #else print the messsage.
    print("ENTER A NUMBER BETWEEN 0 AND 1000")
print("THANK YOU!!!")
    
    
#OUTPUT :
WELCOME!!!
ENTER THE VALUE OF n : 729
9.00
THANK YOU!!!



#PRACTICAL 2.2 :  Aman is playing a game which has 3 levels. if Aman surpasses level 1 give him reward of 1000 coins and if clears level 2 reward him with 2000 coins and if clears level 3 reward him with 3000 coins if he fails any level tell him to try again (*Rewarding and providing restart can be just print statemnts*) (Surpassing of level can be done by defeating each level character consider level 1 character as A level 2 character as B level 3 character as C)

#INPUT
print("welcome, Player")                                                  #print function prints everything under double quotes.
print("\n\n")
print("Level 1")                                                          #level 1
print("")
print("Defeat the boss of level 1 by answering him to proceed to level 2")  
ans1=int(input(" Boss:what is factorial of 7?\n\t"))

if  ans1==5040:                                               #if the player gives correct answer, he is promoted and earns coin.
      print("Congratulations. proceeding to level 2")
      coins=1000
      print ("You have recieved",coins,"coins!!")
else:                                                         #else, he will try again.
      print("You have failed level 1. please retry")
      exit()
    
print("\n\n")
print("Level 2")                                              #level 2
print("")
print("Defeat the boss of level 2 by answering him to proceed to level 3")
ans2=input("Boss:who painted the mona lisa? (answer in lower case only)\n\t") #same conditional form.

if ans2== "leonardo da vinci" or ans2=="da vinci":
       print("Congratulations. proceeding to level 3")
       coins=coins+2000
       print ("You have recieved",coins,"coins!!")
else:
      print("You have failed level 2. please retry")
      exit()
    
print("\n\n")
print("Level 3")                                              #level 3
print("")
print("Defeat the boss of level 3 by answering him to win the game") 
ans3=int(input("Boss:what is the cuberoot of 729?\n\t"))

if ans3==9:                                                  #same conditional form. 
      print("\n\nCongratulations. you have won the game.")
      coins=coins+3000                                       #printing the total coins he wins.
      print ("You have recieved",coins,"coins!!\nit was a fun game!\nyou may now exit the game.")
      exit()
else:
      print("You have failed level 3. please retry")
      exit()
    
    
#OUTPUT :
Welcome, player



Level 1

Defeat the boss of level 1 by answering him to proceed to level 2
 Boss:what is factorial of 7?
	5040
Congratulations. proceeding to level 2
You have recieved 1000 coins!!



Level 2

Defeat the boss of level 2 by answering him to proceed to level 3
Boss:who painted the mona lisa? (answer in lower case only)
	leonardo da vinci
Congratulations. proceeding to level 3
You have recieved 3000 coins!!



Level 3

Defeat the boss of level 3 by answering him to win the game
Boss:what is the cuberoot of 729?
	9


Congratulations. you have won the game.
You have recieved 6000 coins!!
It was a fun game!
You may now exit the game.



#PRACTICAL 2.3 : A student will not be allowed to sit in exam if his/her attendence is less than 75%.
#Take following input from user
#Number of classes held
#Number of classes attended.
#And print
#percentage of class attended
#Is student allowed to sit in exam or not.

#INPUT :
print("WELCOME!!")                                     
class_held = int(input("PLEASE ENTER THE NUMBER OF CLASSES HELD:"))          #taking no. of classes held from user.
class_attended = int(input("PLEASE ENTER THE NUMBER OF CLASSES ATTENDED:"))  #taking no. of classes the student attends from user.
per= (class_attended/class_held)*100                                         #calc. percentage of class attended and printing it.
print("PERCENTAGE OF CLASS ATTENDED : ",per,"%")
if per >= 75:                                           #using if else statement to know if the student is allowed to give exams.
    print("THE STUDENT IS ALLOWED TO SIT IN THE EXAM")
else:
    print("THE STUDENT IS NOT ALLOWED TO SIT IN THE EXAM")
print("THANK YOU!!")


#OUTPUT:
WELCOME!!
PLEASE ENTER THE NUMBER OF CLASSES HELD:12
PLEASE ENTER THE NUMBER OF CLASSES ATTENDED:10
PERCENTAGE OF CLASS ATTENDED :  83.33333333333334 %
THE STUDENT IS ALLOWED TO SIT IN THE EXAM
THANK YOU!!



#PRACTICAL 2.4 : Check whether the triangle is equilateral, scalene, or isosceles

#INPUT
print("WELCOME!!!")
side_1 = int(input("ENTER THE LENGTH OF SIDE 1 OF THE TRIANGLE : ")) #taking the three sides of the triangle.
side_2 = int(input("ENTER THE LENGTH OF SIDE 2 OF THE TRIANGLE : "))
side_3 = int(input("ENTER THE LENGTH OF SIDE 3 OF THE TRIANGLE : "))

if side_1 == side_2 and side_2 == side_3:                            #if all the three sides are equal, it is an equilateral triangle.
    print("THE GIVEN TRIANGLE IS EQUILATERAL")
elif side_1 == side_2 or side_2 == side_3 or side_3 == side_1:       #if two sides are equal, we say it is isosceles.
    print("THE GIVEN TRIANGLE IS ISOSCELES") 
else:                                                                #else, we say it is a scalene triangle.
    print("THE GIVEN TRIANGLE IS SCALENE")
    
print("THANK YOU!!!")


#OUTPUT
WELCOME!!!
ENTER THE LENGTH OF SIDE 1 OF THE TRIANGLE : 10
ENTER THE LENGTH OF SIDE 2 OF THE TRIANGLE : 10
ENTER THE LENGTH OF SIDE 3 OF THE TRIANGLE : 12
THE GIVEN TRIANGLE IS ISOSCELES
THANK YOU!!!

